# Generated by Django 3.1.14 on 2023-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.TextField(default='zor kitob'),
            preserve_default=False,
        ),
    ]
